### ISSUE TITLE
Add gun recoil

### ISSUE THREAD

**Issue by DaCodaz** [khaledhn1/Scorched-Sands#45]

**Comment by khaledhn1** [comment]
There is no recoil anywhere I cannot find it.

**Comment by DaCodaz** [comment]
Sorry the file didn't upload properly

**Comment by DaCodaz** [comment]
btw it is in level 1 not weapon testing

**Comment by DaCodaz** [comment]
The gun recoils upwards but I can't get it back to original position, so I left the else blank.
It also fires outwards from the camera, not the gun.

**Comment by DaCodaz** [comment]
few bugs, need to switch weapon once before it works.
