### ISSUE TITLE
Add Objectives

### ISSUE THREAD

**Issue by khaledhn1** [khaledhn1/Scorched-Sands#51]

**Comment by DaCodaz** [comment]
So the objectives work properly, but i cant get the objective manager to check if there are no objectives

**Comment by khaledhn1** [comment]
just go the easy way and enable/dsiable diffrent scripts to manage the pbjectives thus if no scrips = no objective

**Comment by DaCodaz** [comment]
Hm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
