### ISSUE TITLE
Fix Bug Which causes the game to crash when you kill an enemy ALWAYS

### ISSUE THREAD

**Issue by DaCodaz** [khaledhn1/Scorched-Sands#58]

**Comment by khaledhn1** [comment]
I've not expirienced this issue before if you can give me some details on how to replicate it or send video of you doing it i'll see what i can do

**Comment by khaledhn1** [comment]
I'm sorry i just cant get this to happen unless i ride a car... and even then it's so rare it only happend 2 times in a 30 mins playtest so... yeah idk wtf to do sorry unless you send me video of it happening i'll just assume it's a mac thing and do something else.
