### ISSUE TITLE
Add a mode of transport

### ISSUE THREAD

**Issue by khaledhn1** [khaledhn1/Scorched-Sands#9]

**Comment by DaCodaz** [comment]
Need help with a bug in the vehicle. The character just goes to the car and it goes flying.

**Comment by DaCodaz** [comment]
I think it is because the computer always thinks the variable "CarActive" is always true even though I set it false

**Comment by DaCodaz** [comment]
Fixed cars. One problem. Actually two. 1. khaled fixed it. 2. It works from specific angles only.
